name: FC-Admin auto deploy          # å¤§æ ‡é¢˜
on: [push]
permissions:
  contents: write                   # è®¾ç½®æƒé™ï¼Œå¯å†™ï¼Œä¹Ÿå¯ä»¥ä¸ç”¨é…ç½®ï¼Œv4ç‰ˆæœ¬æ–°å¢çš„
jobs:
  build-and-deploy:                 # å…¶ä¸­ä¸€ä¸ªä»»åŠ¡çš„åç§°ï¼ŒID
    runs-on: ubuntu-latest          # è¿™ä¸ªä»»åŠ¡è¿è¡Œæ‰€éœ€çš„ç¯å¢ƒ
    steps:
      - name: Checkout ğŸ›ï¸           # ç¬¬ä¸€æ­¥ï¼šè·å–æºç 
        uses: actions/checkout@v4   # ä½¿ç”¨çš„å·¥å…·
 
      - name: Install and Build ğŸ”§  # ç¬¬äºŒæ­¥ï¼šä¸‹è½½ä¾èµ–å’Œæ„å»º
        run: |
          npm ci
          npm run build
 
      - name: Deploy ğŸš€             # ç¬¬ä¸‰æ­¥ï¼šéƒ¨ç½²
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist              # éƒ¨ç½²çš„ç›®å½•